### ISSUE TITLE
Error installing pyinstaller

### ISSUE THREAD

**Issue by feliux** [private-dreamnet/dreampower#62]
Building package on dreampower directory (Archlinux) after checkpoints:

>makepkg -si
Installing pyinstaller...
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

any idea to solve this issue? 
TY

**Comment by PommeDroid** [comment]
In order to help you correctly you need to share the PKGBUILD file you are using. What's I can guess from error is, you are using setup.py with --pip_user in virtualenv. This option make pip install use --user option and this not possible to do so in a virtualenv.  Again it's the best guess I can do until you share the PKGBUILD.
